version: "3.9"
   
services:
  db:
    image: mysql
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_sixshop
    networks:
      - sixshop
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  springapp:
    image: sixshop/sixshop:latest
    networks:
      - sixshop
    ports:
      - "8443:8443"
    depends_on:
      db:
        condition: service_healthy
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_sixshop?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    restart: always
networks:
  sixshop: